### ISSUE TITLE
this just got blatantly pasted

### ISSUE THREAD

**Issue by justkamiii** [3V1/EzNuke#1]
https://github.com/ssllllll/DiscordTool/

**Comment by 3V1** [comment]
> https://github.com/ssllllll/DiscordTool/

@justkamiii bruh

**Comment by justkamiii** [comment]
ikr

**Comment by 3V1** [comment]
> ikr

idrc, only thing that kinda pissed me off is that he went ahead and put it like he made it, no credits to me

**Comment by justkamiii** [comment]
AND HE DELETED THE ISSUES TAB LOLOLOL

**Comment by justkamiii** [comment]
what an idiot, https://github.com/ssllllll/DiscordTool/pull/4

**Comment by justkamiii** [comment]
just a quick suggestion, add a license and don't let him steal your code like that again in case of updates

**Comment by 3V1** [comment]
> just a quick suggestion, add a license and don't let him steal your code like that again in case of updates

will do, thanks for letting me know
